spring.datasource.url=jdbc:mysql://localhost:3306/mednext_db
spring.datasource.username=root
spring.datasource.password=Mayank@dns78

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

jwt.secret=mednext_super_secret_key_change_in_prod_256bit_1234567890123456
jwt.expiration=86400000